# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "anatole-zola"

default_language = "en"

title = "Spooky Kabuki Labs"

description = "A other zola theme"

# The URL the site will be built for
base_url = "https://kabuki.dev"

generate_feed = true

taxonomies = [
    {name = "tags"},
]

[extra.social]
github = "Spooky-Kabuki"
twitter = ""
facebook = ""
instagram = ""
dribbble = ""
weibo = ""
linkedin = ""
flickr = ""

[extra.show]
tags = true
links = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
mode = "dark"
title = "Spooky Kabuki Labs"
[languages.en.translations]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Next Page"
last_page = "Last Page"
date_format = "%Y-%m-%d"
title = "Spooky Kabuki Labs"
